# Generated by Django 3.2.13 on 2022-05-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seats', models.JSONField()),
                ('seatPlan', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('num', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('price', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('category', models.PositiveSmallIntegerField()),
                ('lastModifiedBy', models.CharField(max_length=200)),
                ('lastModified', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.hall'),
        ),
    ]
