# Generated by Django 4.0.1 on 2022-05-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_event_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='days',
        ),
    ]
