# Generated by Django 4.0.1 on 2022-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0003_remove_event_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
