# Generated by Django 4.0.1 on 2022-05-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0004_alter_ticket_lastmodified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
