# Generated by Django 4.0.1 on 2022-05-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0007_remove_ticket_day_delete_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
