# Generated by Django 4.0.1 on 2022-05-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0010_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
